name: Baoan Gist Mail Monitor
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python lib
        run: pip install requests beautifulsoup4
      - name: Run monitor script
        run: python monitor.py
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.github.com
          server_port: 465
          username: ${{ shturl.cc/Tb }}
          password: ${{ secrets.GITHUB_TOKEN }}
          from: "Github监控脚本 <noreply@github.com>"
          to: ${{ secrets.MAIL_TO }}
          subject: 【深圳保租房监控-宝安站点】通知
          body: ${{ env.EMAIL_BODY }}
